
services:
  project_db:
    image: postgres:16
    container_name: project_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - project_db_data:/var/lib/postgresql/data
    networks:
      - airflow_net
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"   
      - "9001:9001"   
    env_file:
      - .env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - airflow_net


networks:
  airflow_net:
    external: true
    name: project-air-quality-traffic_36119f_airflow

volumes:
  project_db_data:
  minio_data: