# dashboard/app.py
import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import folium
from streamlit_folium import st_folium
from sqlalchemy import create_engine
from datetime import datetime, timedelta
import os


# Page config

st.set_page_config(page_title="Air Quality", layout="wide")
st.title("Air Quality Predictions")
st.markdown("""
This interactive dashboard presents **NO₂ (Nitrogen Dioxide)** predictions generated by machine learning models
trained on data from **monitoring stations across Madrid**.

It compares **real measured values** against **model predictions**, detects anomalies when the difference
between real and predicted values is significantly high, and provides station-level performance metrics.

**Key features** include an interactive map of monitoring stations, hourly prediction vs. real comparisons,
anomaly detection based on prediction error, and performance metrics per station.
""", unsafe_allow_html=True)


# Station coordinates

STATION_COORDS = {
    4:  (40.4230, -3.7122, "Pza. de España"),
    8:  (40.4213, -3.6822, "Escuelas Aguirre"),
    11: (40.4515, -3.6773, "Ramón y Cajal"),
    16: (40.4400, -3.6392, "Arturo Soria"),
    17: (40.3471, -3.7133, "Villaverde"),
    27: (40.3931, -3.7122, "Barajas"),
    35: (40.4031, -3.6622, "El Pardo"),
    36: (40.4331, -3.7222, "Fdez. Ladreda"),
    38: (40.4431, -3.6522, "Cuatro Caminos"),
    39: (40.4731, -3.7322, "Barrio del Pilar"),
    40: (40.3831, -3.6922, "Vallecas"),
    47: (40.4831, -3.7122, "Sanchinarro"),
    48: (40.3731, -3.7022, "Ensanche Vallecas"),
    50: (40.4931, -3.6822, "Tres Olivos"),
    56: (40.3631, -3.6722, "Mendez Alvaro"),
    57: (40.5031, -3.7222, "Urbanización Embajada"),
    60: (40.3531, -3.7122, "Moratalaz"),
}


# Load data from PostgreSQL

@st.cache_data(ttl=300)
def load_predictions():
    db_url = (
        f"postgresql://{os.environ['POSTGRES_USER']}:{os.environ['POSTGRES_PASSWORD']}"
        f"@project_db:5432/{os.environ['POSTGRES_DB']}"
    )
    engine = create_engine(db_url)
    df = pd.read_sql("SELECT * FROM predictions ORDER BY timestamp DESC", engine)
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    df["estacion"] = df["estacion"].astype(int)
    df["error"] = (df["y_real"] - df["y_pred"]).abs()
    df["alerta"] = df["error"] > df.groupby("estacion")["error"].transform("mean") * 2
    return df

df = load_predictions()


# Session state

station_options = sorted(df["estacion"].unique().tolist())

if "estacion_sel" not in st.session_state:
    st.session_state.estacion_sel = station_options[0]

if "map_center" not in st.session_state:
    coords = STATION_COORDS.get(st.session_state.estacion_sel, (40.41, -3.70, ""))
    st.session_state.map_center = [coords[0], coords[1]]
    st.session_state.map_zoom = 11


# Sidebar

with st.sidebar:
    st.title("Settings")

    estacion_sel = st.selectbox(
        "Select a station",
        options=station_options,
        index=station_options.index(st.session_state.estacion_sel),
        format_func=lambda x: f"{x} - {STATION_COORDS.get(x, ('','',''))[2]}",
    )
    if estacion_sel != st.session_state.estacion_sel:
        st.session_state.estacion_sel = estacion_sel
        st.rerun()

    st.divider()
    st.markdown("### Time Range")
    dias = st.slider("Last N days", 1, 30, 7)
    cutoff = datetime.now() - timedelta(days=dias)

    st.divider()
    df_sidebar = df[df["estacion"] == st.session_state.estacion_sel]
    st.metric("Total predictions", len(df_sidebar))
    st.metric("Active alerts", int(df_sidebar["alerta"].sum()))
    last_ts = df_sidebar["timestamp"].max()
    st.metric("Last prediction", last_ts.strftime("%H:%M %d/%m") if pd.notna(last_ts) else "N/A")


# Map

st.header("Madrid Monitoring Stations Map")

df_map_stats = df.groupby("estacion").agg(
    error_medio=("error", "mean"),
    alertas=("alerta", "sum"),
).reset_index()

coords = STATION_COORDS.get(st.session_state.estacion_sel, (40.41, -3.70, ""))
m = folium.Map(location=[coords[0], coords[1]], zoom_start=11)

for _, row in df_map_stats.iterrows():
    estacion = int(row["estacion"])
    coord = STATION_COORDS.get(estacion)
    if not coord:
        continue

    alertas = int(row["alertas"])
    error = round(row["error_medio"], 2)
    color = "red" if alertas > 5 else "orange" if alertas > 0 else "green"
    selected = estacion == st.session_state.estacion_sel

    icon_html = f"""
    <div style="
        background-color:{color};
        color:white;
        border-radius:50%;
        width:{'36px' if selected else '28px'};
        height:{'36px' if selected else '28px'};
        display:flex;
        align-items:center;
        justify-content:center;
        font-weight:bold;
        border: {'3px solid black' if selected else '2px solid white'};
        font-size:{'13px' if selected else '11px'};
    ">
        {estacion}
    </div>
    """
    popup_text = f"<b>Station {estacion}</b><br>{coord[2]}<br>Avg Error: {error}<br>Alerts: {alertas}"
    folium.Marker(
        location=[coord[0], coord[1]],
        popup=folium.Popup(popup_text, max_width=200),
        tooltip=str(estacion),
        icon=folium.DivIcon(html=icon_html)
    ).add_to(m)

col1, col2 = st.columns([2, 1], gap="medium")

with col1:
    map_result = st_folium(
        m,
        height=450,
        returned_objects=["last_object_clicked_tooltip"],
        use_container_width=True
    )

    clicked = map_result.get("last_object_clicked_tooltip")
    if clicked:
        try:
            clicked_int = int(clicked)
            if clicked_int in station_options and clicked_int != st.session_state.estacion_sel:
                st.session_state.estacion_sel = clicked_int
                st.rerun()
        except (ValueError, TypeError):
            pass

with col2:
    nombre = STATION_COORDS.get(st.session_state.estacion_sel, ('','',''))[2]
    st.subheader(f"Station {st.session_state.estacion_sel}")
    st.markdown(f"**{nombre}**")

    df_sel = df[
        (df["estacion"] == st.session_state.estacion_sel) &
        (df["timestamp"] >= cutoff)
    ]

    rmse = (df_sel["error"] ** 2).mean() ** 0.5 if not df_sel.empty else 0
    mae = df_sel["error"].mean() if not df_sel.empty else 0
    alertas_count = int(df_sel["alerta"].sum()) if not df_sel.empty else 0

    col_a, col_b = st.columns(2)
    col_a.metric("RMSE", f"{rmse:.2f}")
    col_b.metric("MAE", f"{mae:.2f}")
    st.metric("Alerts detected", alertas_count)

    if alertas_count > 0:
        alertas_df = df_sel[df_sel["alerta"]]
        horas = alertas_df["timestamp"].dt.strftime("%H:%M %d/%m").tolist()
        if rmse > 10:
            st.error(f"❌ ALERT: Severe anomalies detected at {', '.join(horas[:5])}")
        else:
            st.warning(f"⚠️ Anomalies detected at {', '.join(horas[:5])}")
    else:
        st.success("✅ No anomalies detected in selected period")


st.divider()
nombre = STATION_COORDS.get(st.session_state.estacion_sel, ('','',''))[2]
st.subheader(f"Predicted vs Real — Station {st.session_state.estacion_sel} ({nombre})")

df_chart = df[
    (df["estacion"] == st.session_state.estacion_sel) &
    (df["timestamp"] >= cutoff)
].sort_values("timestamp")

if df_chart.empty:
    st.info("No data available for the selected filters.")
else:
    alertas_df = df_chart[df_chart["alerta"]]

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=df_chart["timestamp"], y=df_chart["y_real"],
        mode="lines", name="Real",
        line=dict(color="royalblue", width=2)
    ))
    fig.add_trace(go.Scatter(
        x=df_chart["timestamp"], y=df_chart["y_pred"],
        mode="lines", name="Predicted",
        line=dict(color="orange", dash="dash", width=2)
    ))
    if not alertas_df.empty:
        fig.add_trace(go.Scatter(
            x=alertas_df["timestamp"], y=alertas_df["y_real"],
            mode="markers", name="Alert",
            marker=dict(color="red", size=10, symbol="x")
        ))

    fig.update_layout(
        height=400,
        xaxis_title="Date",
        yaxis_title="NO₂ (µg/m³)",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        margin=dict(l=0, r=0, t=10, b=0)
    )
    st.plotly_chart(fig, use_container_width=True)

    if not alertas_df.empty:
        with st.expander(f"⚠️ {len(alertas_df)} alerts detected — see details"):
            st.dataframe(
                alertas_df[["timestamp", "y_real", "y_pred", "error"]].rename(columns={
                    "timestamp": "Date", "y_real": "Real", "y_pred": "Predicted", "error": "Error"
                }),
                use_container_width=True
            )


# Metrics per station

st.divider()
st.subheader("Performance Metrics by Station")

df_metrics = df.groupby("estacion").agg(
    rmse=("error", lambda x: (x**2).mean()**0.5),
    mae=("error", "mean"),
    alerts=("alerta", "sum"),
    predictions=("y_pred", "count")
).reset_index().round(2)

df_metrics["estacion"] = df_metrics["estacion"].astype(int)
df_metrics["station_name"] = df_metrics["estacion"].map(
    lambda x: STATION_COORDS.get(x, ('','',''))[2]
)
df_metrics = df_metrics[["estacion", "station_name", "rmse", "mae", "alerts", "predictions"]]
df_metrics.columns = ["Station", "Name", "RMSE", "MAE", "Alerts", "Predictions"]

st.dataframe(df_metrics, use_container_width=True)